In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

#붓꽃 데이터셋 불러오기
iris = load_iris()  #붓꽃 데이터
X, y = iris.data, iris.target  #특성 데이터와 타깃(품종) 데이터 분리

#데이터를 학습용과 테스트용으로 나누기
#random_state는 결과 재현성을 위해 고정
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#랜덤 포레스트 분류기 생성, 재현 가능한 결과를 위해 random_state 설정
model = RandomForestClassifier(random_state=42)

#학습 데이터로 모델 학습 진행
model.fit(X_train, y_train)

def run_iris_classifier():
    #무한 반복을 통해 사용자가 종료하기 전까지 계속 실행
    while True:
        print("\n붓꽃값(SL, SW, PL, PW)를 입력하여 품종을 알아보도록 하겠습니다.")
        try:
            #각 꽃받침, 꽃잎 길이/너비 값을 실수 형태로 입력받기
            sepal_length = float(input("1. 붓꽃의 '꽃받침 길이(Sepal Length)' 값을 입력해주세요(4~8 사이의 값 입력): "))
            sepal_width = float(input("2. 붓꽃의 '꽃받침 너비(Sepal Width)' 값을 입력해주세요(2.0~4.5 사이의 값 입력): "))
            petal_length = float(input("3. 붓꽃의 '꽃잎 길이(Petal Length)' 값을 입력해주세요(1~7 사이의 값 입력): "))
            petal_width = float(input("4. 붓꽃의 '꽃잎 너비(Petal Width)' 값을 입력해주세요(0.1~2.5 사이의 값 입력): "))
        except ValueError:
            #만약 입력이 숫자가 아니면 에러를 알리고 다시 처음으로 돌아감
            print("숫자만 입력해 주세요. 다시 시도합니다.")
            continue
        
        #입력값들을 리스트로 만들어서 모델에 넣기 위해 준비
        features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        
        #입력값을 리스트 형태로 출력하여 확인 가능하게 함
        print(f"[{sepal_length} {sepal_width} {petal_length} {petal_width}]")
        
        #학습된 모델에 입력값을 넣고 예측한 품종 인덱스 받기
        pred_idx = model.predict(features)[0]
        
        #인덱스를 붓꽃 품종 문자열로 변환
        pred_species = iris.target_names[pred_idx]
        
        #최종 예측 결과를 화면에 출력
        print(f"당신이 입력한 품종은 '{pred_species}' 입니다.")
        print("="*30)  #구분선 출력
        
        #계속 진행 여부를 묻는 반복문
        while True:
            cont = input("계속 진행하시겠습니까? (0: 종료, 1: 진행): ")
            if cont == '1':
                print("계속 진행하겠습니다.")
                break  #1 입력 시 바깥 while문 계속 진행
            elif cont == '0':
                print("종료하겠습니다")
                return  #0 입력 시 함수 종료 -> 프로그램 종료
            else:
                #0 혹은 1이 아닌 다른 값 입력 시 올바른 입력을 안내
                print("0 또는 1만 입력해주세요.")

#파이썬 프로그램이 직접 실행될 때만 아래 코드가 동작하게 함
if __name__ == "__main__":
    run_iris_classifier()


붓꽃값(SL, SW, PL, PW)를 입력하여 품종을 알아보도록 하겠습니다.
[5.1 2.5 6.2 2.2]
당신이 입력한 품종은 'virginica' 입니다.
계속 진행하겠습니다.

붓꽃값(SL, SW, PL, PW)를 입력하여 품종을 알아보도록 하겠습니다.
[4.1 3.7 3.1 0.5]
당신이 입력한 품종은 'setosa' 입니다.
계속 진행하겠습니다.

붓꽃값(SL, SW, PL, PW)를 입력하여 품종을 알아보도록 하겠습니다.
[7.5 3.6 5.4 1.6]
당신이 입력한 품종은 'virginica' 입니다.
종료하겠습니다
