In [ ]:
import numpy as np
list1 = [95, 63, 62, 78, 60, 73, 77, 97]

arr1 = np.array(list1)

In [ ]:
arr1 > 60

In [ ]:
arr1[[True, False, True, True, True, False, True, True, True]]

In [ ]:
arr1[arr1>60]

In [1]:
import numpy as np
import random
list_1 = []

for i in range(20):
    list_1.append(random.randint(1,100))

rarr = np.array(list_1)
arr2 = rarr.reshape(5, -1)

print(arr2)

print("=========== axis = 0 행기준 위아래 ===========")
ar1 = np.sort(arr2, axis = 0)
print(ar1)

print("=========== axis = 1 열기준 좌우 ===========")
ar2 = np.sort(arr2, axis = 1)
print(ar2)

[[ 79  39  34  66]
 [100  34  79  65]
 [ 83  84  38  15]
 [ 35  47  97  79]
 [ 79  46   4  48]]
=========== axis = 0 행기준 위아래 ===========
[[ 35  34   4  15]
 [ 79  39  34  48]
 [ 79  46  38  65]
 [ 83  47  79  66]
 [100  84  97  79]]
=========== axis = 1 열기준 좌우 ===========
[[ 34  39  66  79]
 [ 34  65  79 100]
 [ 15  38  83  84]
 [ 35  47  79  97]
 [  4  46  48  79]]


In [3]:
print(rarr)

np.sort(rarr)
print(np.sort(rarr))

[ 79  39  34  66 100  34  79  65  83  84  38  15  35  47  97  79  79  46
   4  48]
[  4  15  34  34  35  38  39  46  47  48  65  66  79  79  79  79  83  84
  97 100]


In [4]:
import pandas as pd

data = {'id' : ['1000','1001','1002','1003','1004','1005'],
        'name' : ['Steve','James','John','Jane','Paul','Tony'],
        'score' : [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data, index = [0,1,2,3,4,5])

print(df)

print(df.values)
print(df.index)
print(df.columns)
print(df.info())

     id   name  score
0  1000  Steve  90.72
1  1001  James  78.09
2  1002   John  98.43
3  1003   Jane  64.19
4  1004   Paul  81.30
5  1005   Tony  99.14
[['1000' 'Steve' 90.72]
 ['1001' 'James' 78.09]
 ['1002' 'John' 98.43]
 ['1003' 'Jane' 64.19]
 ['1004' 'Paul' 81.3]
 ['1005' 'Tony' 99.14]]
Index([0, 1, 2, 3, 4, 5], dtype='int64')
Index(['id', 'name', 'score'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      6 non-null      object 
 1   name    6 non-null      object 
 2   score   6 non-null      float64
dtypes: float64(1), object(2)
memory usage: 192.0+ bytes
None
