In [ ]:
# 실습예제 1
import numpy as np

scores = [88, 92, 75, 100, 89, 95, 73, 68, 85, 90, 78, 82, 96, 87, 91]

#1. numpy 배열 변환
arr = np.array(scores) 

#2.
mean_score = np.mean(arr) # 평균
max_score = np.max(arr) # 최댓값
min_score = np.min(arr) # 최솟값
median_score = np.median(arr) # 중앙값

#3.
print(arr[arr >= 80]) # 80점 이상 점수출력
count_below_70 = np.sum(arr <= 70) # 70점 이하
sorted_scores = np.sort(arr) # 오름차순

# 5점 추가 (100점 초과x)
added_scores = np.minimum(arr + 5, 100)  

[ 88  92 100  89  95  85  90  82  96  87  91]


In [11]:
# 실습예제 2
import numpy as np

class_A = np.array([78,75,90,88,76,95,89,84,91,87,80,93,72,99,83,77,94,86,81,79])
class_B = np.array([82,79,88,92,75,89,90,80,86,85,78,96,74,100,82,76,97,84,83,81])

#1. 평균
mean_A = np.mean(class_A)
mean_B = np.mean(class_B)

print(f"Class A 평균 점수: {mean_A}")
print(f"Class B 평균 점수: {mean_B}")

if mean_A > mean_B:
    print("A의 평균 점수가 더 높습니다.")
elif mean_B > mean_A:
    print("B의 평균 점수가 더 높습니다.")
else:
    print("평균 점수가 같습니다.")

#2. 중앙값, 표준편차
median_A = np.median(class_A)
median_B = np.median(class_B)
std_A = np.std(class_A, ddof=0)
std_B = np.std(class_B, ddof=0)

#3. 최상위 5명 점수
top5_A = np.sort(class_A)[-5:]
top5_B = np.sort(class_B)[-5:]

mean_top5_A = np.mean(top5_A)
mean_top5_B = np.mean(top5_B)

print(f"A 최상위 5명 점수: {top5_A}, 평균: {mean_top5_A}")
print(f"B 최상위 5명 점수: {top5_B}, 평균: {mean_top5_B}")

if mean_top5_A > mean_top5_B:
    print("A의 최상위 5명 평균 점수가 더 높습니다.")
elif mean_top5_B > mean_top5_A:
    print("B의 최상위 5명 평균 점수가 더 높습니다.")
else:
    print("최상위 5명 평균 점수가 같습니다.")

#4. 80점 이상 비율
ratio_A = np.sum(class_A >= 80) / len(class_A)
ratio_B = np.sum(class_B >= 80) / len(class_B)

print(f"Class A 80점 이상 학생 비율: {ratio_A:.2%}")
print(f"Class B 80점 이상 학생 비율: {ratio_B:.2%}")

if ratio_A > ratio_B:
    print("A가 80점 이상인 학생 비율이 더 높습니다.")
elif ratio_B > ratio_A:
    print("B가 80점 이상인 학생 비율이 더 높습니다.")
else:
    print("80점 이상 학생 비율이 같습니다.")

Class A 평균 점수: 84.85
Class B 평균 점수: 84.85
평균 점수가 같습니다.
A 최상위 5명 점수: [91 93 94 95 99], 평균: 94.4
B 최상위 5명 점수: [ 90  92  96  97 100], 평균: 95.0
B의 최상위 5명 평균 점수가 더 높습니다.
Class A 80점 이상 학생 비율: 70.00%
Class B 80점 이상 학생 비율: 75.00%
B가 80점 이상인 학생 비율이 더 높습니다.


In [19]:
# 실습예제 3
import numpy as np

City_temps = [
[12.3, 14.1, 15.8, 13.5, 16.2, 17.0, 14.8], # 서울
 [15.2, 16.8, 18.1, 17.4, 19.0, 20.5, 18.6], # 부산
 [14.5, 15.9, 17.3, 16.0, 18.2, 19.8, 17.5], # 대구
 [13.8, 15.2, 16.5, 14.9, 17.0, 18.3, 16.1] # 광주
]

City_temps = np.array(City_temps) #numpy 배열 변환

cities = ['서울', '부산', '대구', '광주']

#1. 7일간 평균기온(행 방향 평균 axis=1)
average_temps = np.mean(City_temps, axis=1)

#2. 최저 최고 기온 (행 기준 axis=1)
min_temps = np.min(City_temps, axis=1)
max_temps = np.max(City_temps, axis=1)

#3. 전국 평균 기온 (열 기준 axis=0)
daily_avg_temps = np.mean(City_temps, axis=0)

#4. 16도 이상인 날 인덱스 추출
days_above_16 = np.where(daily_avg_temps >= 16)[0]

print("7일 중 평균 기온이 16도 이상인 날과 해당 도시들의 기온:\n")

# 평균 16도 이상인 날 도시별 기온 출력
for i in range(len(days_above_16)):
    day = days_above_16[i]
    print(f"{day + 1}일차 도시별 기온:")
    for j in range(len(cities)):
        print(f"{cities[j]}: {City_temps[j][day]}도")

#5. 섭씨 -> 화씨 변환
City_temps_F = City_temps * 9/5 + 32

# 각 도시별 평균 화씨 기온 계산 (행별 평균)
average_F = np.mean(City_temps_F, axis=1)

#6. 기온 차이 계산
temp_diffs = max_temps - min_temps

# 가장 큰 기온 차이 인덱스
max_diff_index = np.argmax(temp_diffs)

print(f"기온 변화가 가장 심한 도시: {cities[max_diff_index]}")

7일 중 평균 기온이 16도 이상인 날과 해당 도시들의 기온:

3일차 도시별 기온:
서울: 15.8도
부산: 18.1도
대구: 17.3도
광주: 16.5도
5일차 도시별 기온:
서울: 16.2도
부산: 19.0도
대구: 18.2도
광주: 17.0도
6일차 도시별 기온:
서울: 17.0도
부산: 20.5도
대구: 19.8도
광주: 18.3도
7일차 도시별 기온:
서울: 14.8도
부산: 18.6도
대구: 17.5도
광주: 16.1도
기온 변화가 가장 심한 도시: 부산


In [20]:
# 실습예제 4
import numpy as np
cost_price = [12000, 8500, 15000, 9900, 21000, 30000, 17500, 19900, 12500, 28000]
sell_price = [15000, 10000, 18000, 12000, 25000, 35000, 21000, 23000, 15500, 31000]

# numpy 배열 변환
cost_price = np.array(cost_price)
sell_price = np.array(sell_price)

# 이익 계산
profit = sell_price - cost_price

# 최대 이익, 인덱스 구하기
max_profit = np.max(profit)
max_index = np.argmax(profit)

print(f"가장 높은 이익을 내는 제품의 색인: {max_index}")
print(f"가장 높은 이익 금액: {max_profit}원")

# 이익률 계산
profit_rate = (profit / cost_price) * 100


# 원가 15,000 이하, 이익 3,000 이상 조건 변수설정
condition = (cost_price <= 15000) & (profit >= 3000)

# 조건에 맞는 인덱스 추출
selected_indices = np.where(condition)[0]

print("원가 15,000원 이하에 이익 3,000원 이상인 제품의 색인:")
print(selected_indices)


# 판매가 20,000원 이상 제품 필터링
high_price_condition = sell_price >= 20000

# 15% 할인된 가격 계산
discounted_price = sell_price * 0.85

# 할인 후 가격이 18,000원 이상인 제품 필터링
final_condition = discounted_price >= 18000

# 두 조건 모두 만족하는 인덱스 추출
selected_indices = np.where(high_price_condition & final_condition)[0]

print("할인 후 가격이 18,000원 이상인 20,000원 이상 판매 제품의 색인:")
print(selected_indices)

가장 높은 이익을 내는 제품의 색인: 5
가장 높은 이익 금액: 5000원
원가 15,000원 이하에 이익 3,000원 이상인 제품의 색인:
[0 2 8]
할인 후 가격이 18,000원 이상인 20,000원 이상 판매 제품의 색인:
[4 5 7 9]


In [ ]:
# 실습예제 5

In [ ]:
# 실습예제 6